[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
build_info = true
extra_output = ["storageLayout"]
gas_reports = ["Recall"]
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 1000000
ffi = true
ast = true
via_ir = true

[fmt]
# These are all of the `forge fmt` defaults
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = 'long'
multiline_func_header = 'attributes_first'
quote_style = 'double'
number_underscore = 'preserve'
single_line_statement_blocks = 'preserve'
# Custom settings
sort_imports = true
wrap_comments = true

[rpc_endpoints]
localnet_parent = "http://127.0.0.1:8545"
localnet_subnet = "http://127.0.0.1:8645"
testnet_parent = "https://api.calibration.node.glif.io/rpc/v1"
testnet_subnet = "https://evm.node-0.testnet.recall.network"
devnet = "http://127.0.0.1:8545"
# Note: placeholder; mainnet is not available yet
mainnet_parent = "https://api.calibration.node.glif.io/rpc/v1"
mainnet_subnet = "https://evm.node-0.testnet.recall.network"
