[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
build_info = true
extra_output = ["storageLayout"]
gas_reports = ["Hoku"]
ffi = true
ast = true

[fmt]
# These are all the `forge fmt` defaults
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = 'long'
multiline_func_header = 'attributes_first'
quote_style = 'double'
number_underscore = 'preserve'
single_line_statement_blocks = 'preserve'
# Custom settings
wrap_comments = true