name: Run Forge Tests with Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y lcov  # Install genhtml (comes with lcov)
          npm install --save-dev foundry-rs/forge-coverage

      - name: Generate Coverage Report
        run: |
          forge coverage --ffi --report lcov -C ./src  # Generate lcov.info
          if [ "$(uname)" = "Darwin" ]; then  # MacOS logic
            genhtml -o coverage_report lcov.info --branch-coverage --ignore-errors category;
          else  # Linux logic
            genhtml -o coverage_report lcov.info --branch-coverage;
          fi

      - name: Display Coverage Summary
        run: cat lcov.info
